# Generated by Django 5.1.7 on 2025-04-02 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='favorite_color',
            new_name='school',
        ),
    ]
